### ISSUE TITLE
SQLite Problem creating tables 

### ISSUE THREAD

**Issue by LexShadow** [DanWin/le-chat-php#104]
There is a bug, if I set it to sqlite as I don't have mysql for less attack vectors and resources but soon as I try set it up I get 

Warning: PDO::prepare(): SQLSTATE[HY000]: General error: 1 no such table: 

The sqlite file is created but after that it's does that error, the part that installs the db seems to be missing I see a trigger for it ever.

The file size is 0 so there is no date been written to it

Windows tested with Xampp, Laragon Apache and Nginx, 

```
Warning: PDO::prepare(): SQLSTATE[HY000]: General error: 1 no such table: main_settings in chat.php on line 4288

Fatal error: Uncaught Error: Call to a member function execute() on bool in chat.php:4289 
Stack trace: 
#0 chat.php(3481): get_setting('imgembed') 
#1 chat.php(379): send_headers() 
#2 chat.php(916): print_start('init') 
#3 chat.php(4373): send_init() 
#4 chat.php(51): check_db() 
#5 {main} thrown in chat.php on line 4289
```

**Comment by LexShadow** [comment]
The lines might be a few lines off, but not by much.

**Comment by DanWin** [comment]
Thanks, the last few commits should solve all SQLite related issues. Let me know if you find anything else.

**Comment by LexShadow** [comment]
This did work but in the settings of the app 

`Enable file uploads`
is no longer a true and false it's a number value box
![image](https://user-images.githubusercontent.com/70896639/119332814-0673fd80-bc81-11eb-9158-149c8b5e83da.png)

**Comment by DanWin** [comment]
Yes, I've just created #105 for it. The number you can add here is the lowest user status which is allowed to upload files. If you set it to for example `3`, then only members can upload a file.
