### ISSUE TITLE
Working with the CSS Stylesheets

### ISSUE THREAD

**Issue by F1nx** [DanWin/le-chat-php#106]
To use the stylesheets embedded in the main PHP file, I was curious to know if there was an easy way of going about getting it besides curling the hosted HTML page and extracting the CSS.

**Comment by DanWin** [comment]
Do you mean the one that's hardcoded in the script? You can take it from the `prepare_stylesheets` function https://github.com/DanWin/le-chat-php/blob/master/chat.php#L265
If you were talking about the configured styles that a super admin can configure in setup, that is only easily accessible to the super admin in the setup or export section and as a user you can take it from the html you get back when opening the chat.
