### ISSUE TITLE
Confusion on message encryption with public, staff, admin notes.

### ISSUE THREAD

**Issue by Deepnerd** [DanWin/le-chat-php#115]
![Capture 3](https://user-images.githubusercontent.com/65068062/130949564-dac0b792-f902-4c2b-b97c-673055b513d2.PNG)

So when I saved an public note while || define('MSGENCRYPTED', true) ||  in the settings, public notes were showing like this.
![Capture 1](https://user-images.githubusercontent.com/65068062/130949094-ceea59d1-37ad-4294-a8ee-e86a78ce4bf0.PNG)

BUT! When I saved a public note while  || define('MSGENCRYPTED', false) || in the settings, public notes were normal.
![Capture 4 - after false encryption](https://user-images.githubusercontent.com/65068062/130949328-f6a803f0-4d87-428a-b6ef-221edcc3a8e2.PNG)

So why my public notes also encrypting like messages to the database and showing that encrypted data to public notes without showing the normal input? I think this is same in admin, staff notes also. but it's good to encrypt private, staff, admin notes but without showing that encrypted data, only showing the normal input back in the chat. And also no need to encrypt public notes since it's public. Is there a way to solve this while I'm using message encryption? Thank you daniel.

**Comment by DanWin** [comment]
Thanks, the public notes feature wasn't written by me, but apparently I haven't checked the code thoroughly enough, before adding it. The other day I fixed a few other issues with it. Luckily it's an easy fix, as there is only a call to the decryption method missing.

**Comment by Deepnerd** [comment]
Thank you daniel! :D
