### ISSUE TITLE
Services Down?

### ISSUE THREAD

**Issue by SlidingHorn** [DanWin/le-chat-php#116]
I apologize for bugging you here, but I couldn't find any other way to contact you other than through GitHub, and I assume your email server isn't working right now...

It appears that your danwin1210.me site is down, as well as (at least) the XMPP service.

I'm sure you'd probably see it without me notifying you, but figured I'd do so just in case. 

When attempting to load the website, I get:

```
Secure Connection Failed

An error occurred during a connection to danwin1210.me. PR_END_OF_FILE_ERROR
```

and attempting to connect to XMPP yields:

`(danwin1210.me) Received zero data on _read_async()`

Not sure if either of those errors helps.

**Comment by DanWin** [comment]
Hello,

yes thanks for trying to reach me. Yesterday evening one the servers micro sd card gave up, which effectively rendered the cluster unusable. After attempting a data recovery, it was obvious that 75% of the data became unreadable, so I've had to re-install a completely fresh cluster node and re-distribute the data across all 3 nodes. At least the new node is now fully powered by USB SSD and does no longer need a micro sd card for the OS.
All services should be back up now, but I might have missed something. let me know if there are any more issues.
