### ISSUE TITLE
Lil Help

### ISSUE THREAD

**Issue by ToresAlan** [DanWin/le-chat-php#117]
I am new to php so is there any possibility for someone to send me a  vid of how to set this up or more clear intructions

**Comment by DanWin** [comment]
Hello, what exactly are you stuck with? If you want to run your own server, you will have to install a web server like nginx, apache or similar and PHP, as well as a database server like mysql. For performance it's best to use the PHP-FPM. Running this yourself can be confusing if you never set it up before, but there are many tutorials like for example this one: https://www.digitalocean.com/community/tutorials/how-to-install-linux-nginx-mariadb-php-lemp-stack-on-debian-10

If you want to run the chat on an existing hosting service, or you've completed installing the software required to run it, then all you need to do is create a database user and add this user, along with the Database it manages at the configuration section at the bottom of the chat.php script.

**Comment by ToresAlan** [comment]
I am using Apache and MySQL, I am using windows since I am new to hosting and find GUI easier for this instance, my only problem is installing PHP into MySQL so it recognizes the code.

**Comment by ToresAlan** [comment]
Im just a bit confused n how to connect the php file to database

**Comment by ToresAlan** [comment]
Im just a bit confused n how to connect the php file to database, I am using xamp on windows

**Comment by ToresAlan** [comment]
Hello again, sorry for late reply, Im just having trouble adding people as admin or moderator, and as a super admin or what not how do I access the public wait room so I can let people in.

**Comment by outofthecommon** [comment]
first you have to register the "nick" as an applicant or member, then you can modify the "nick" in the admin section to every rank, except senior admin..
