### ISSUE TITLE
Error/Bug

### ISSUE THREAD

**Issue by Hartomeister** [DanWin/le-chat-php#125]
I launched script and got an error: "Fatal error: No connection to database!"

Do you know what could happen?

**Comment by DanWin** [comment]
As the error message indicates, there is no connection to the database. Make sure you correctly provided the database connection details at the end of the chat.php script. If they are correct, try connecting to the database with another tool, to make sure the connection works.
In case you are using the SQLite database, make sure that the path to the database file is writeable by your webserver user.
