### ISSUE TITLE
White screen after Initial Setup page

### ISSUE THREAD

**Issue by codinPenguin** [DanWin/le-chat-php#127]

**Comment by DanWin** [comment]
Can you check your webservers error log and paste the content here? Otherwise we will be unable to help you.

**Comment by codinPenguin** [comment]
> Can you check your webservers error log and paste the content here? Otherwise we will be unable to help you.

sure this is what it says.

[Wed Aug 10 00:00:32.202319 2022] [mpm_prefork:notice] [pid 773] AH00163: Apache/2.4.52 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
[Wed Aug 10 00:00:32.202401 2022] [core:notice] [pid 773] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 10 00:00:32.203035 2022] [mpm_prefork:notice] [pid 773] AH00169: caught SIGTERM, shutting down
[Wed Aug 10 00:02:27.487589 2022] [mpm_prefork:notice] [pid 754] AH00163: Apache/2.4.52 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
[Wed Aug 10 00:02:27.578198 2022] [core:notice] [pid 754] AH00094: Command line: '/usr/sbin/apache2'
[Wed Aug 10 00:29:58.736203 2022] [php7:error] [pid 829] [client 172.68.118.80:27064] script '/var/www/html/xmlrpc.php' not found or unable to stat

**Comment by DanWin** [comment]
Either there is no error in the script and it exited cleanly, or the time frame you looked into the logs and the white screen do not match. When you trigger the white screen, can you check if there is anything added to the logs? The snippet you shared doesn't indicate any errors.
