### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by gentledawn** [DanWin/le-chat-php#130]
While testing this script, I found this security flaw.

Steps to reproduce:

1. On new browser window/tab, open the chat page
2. Login
3. Logout
4. Click "Back to the login page" button
5. On browser, click and hold the Go Back button
6. Click the very bottom page
7. Click Go Forward button
8. Got a "Document Expired" page, then click the browser's Reload button
9. Got a pop up, click Resend
10. Got logged in

This shouldn't be happened.

**Comment by DanWin** [comment]
Hello @gentledawn ,

thanks for pointing this out. For those users that allow JavaScript, this is now fixed. The history state saved by the browser is emptied on every request.
