### ISSUE TITLE
Vulnerable Moderator Approval and Captcha

### ISSUE THREAD

**Issue by gittyspirit** [DanWin/le-chat-php#136]
In Black Hat Chat, Spamming bots easily bypass moderator's approval and Captcha.  @n0tr1v wrote a bhcli to bypass these things. Please update the code and make the moderator approval and captcha stronger.

**Comment by cypherbits** [comment]
@gittyspirit in free open source software you are free to make a pull request... Maybe the main dev has no time right now.

**Comment by DanWin** [comment]
Hello @gittyspirit , thanks for opening the ticket. The captchas are indeed fairly easy to break, if you build a bot that applies OCR on the image. More distortion would be necessary, to make it harder to identify the characters.
Bypassing moderator approval is however something I have so far been unaware of. This should not be possible, unless the bot uses a moderator account to approve accounts. Do you have any more details on how the vulnerability is supposed to work? Or if possible the source code to `bhcli`?
If you want to keep the details private, you can also securely report the vulnerability details to me via email at daniel@danwin1210.de

**Comment by FBIandEuropol** [comment]
I think if we cancel captcha for mods, we need to enforce a new rule: passwords has to be a curtain length and of curtain complexity. the "Staff" AKA super mods and the Admins should be able to track the password complexity of the Members.I would suggest that  passwords should be at least 15 characters, with upper and lowercase letters, numbers and symbols.

some members may not remember their password so maybe a recovery system will help too,

regarding the complexity of the captcha I would suggest increasing the captcha to 12 characters instead on 6 , and include letters as well both upper and lowercase. also I'm not an expert of spambots but I thin reducing the saturation and contrast will help. hate to say it but the Ableonion clock captcha seems to work as well
