### ISSUE TITLE
Fail to deploy le-chat-php to Replit

### ISSUE THREAD

**Issue by gittyspirit** [DanWin/le-chat-php#138]
`ndefined array key "Entrance" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Leaving" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Member registered" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Applicant registered" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Kicked" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Multiple kicked" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "All kicked" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Room cleaned" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Message to all" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Message to members only" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Message to staff only" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Message to admins only" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Private message" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Attachement" in /home/runner/le-chat-php/index.php on line 3779

Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3779

Warning: Undefined array key "Background colour" in /home/runner/le-chat-php/index.php on line 3785

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3785

Warning: Undefined array key "Font colour" in /home/runner/le-chat-php/index.php on line 3785

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home/runner/le-chat-php/index.php on line 3785

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3746

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3747

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3748

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3749

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3750

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3751

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3755

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3756

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3765

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3766

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3767

Warning: Cannot modify header information - headers already sent by (output started at /home/runner/le-chat-php/index.php:3779) in /home/runner/le-chat-php/index.php on line 3768`

These are logs in my chat. I use [Replit](https://replit.com) with a PHP Web Server Template. I imported Danwin/le-chat-php repo from github. What's more, I used [freedb](https://freedb.tech) as my external db. But it showed these error logs when I apply the chat settings. What should I do then?

**Comment by gittyspirit** [comment]
What's more, When guests entered this chat. it showed these errors.

`
Deprecated: Invalid characters passed for attempted conversion, these have been ignored in /home/runner/le-chat-php/index.php on line 3966

Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'bgcolour' at row 1 in /home/runner/le-chat-php/index.php:2676 Stack trace: #0 /home/runner/le-chat-php/index.php(2676): PDOStatement->execute(Array) #1 /home/runner/le-chat-php/index.php(2582): write_new_session('fjdksds2') #2 /home/runner/le-chat-php/index.php(2749): create_session(false, 'Nobody', 'fjdksds2') #3 /home/runner/le-chat-php/index.php(103): check_login() #4 /home/runner/le-chat-php/index.php(72): route() #5 {main} thrown in /home/runner/le-chat-php/index.php on line 2676`

**Comment by gittyspirit** [comment]
It's just like problem #137 . Only Super Admin can enter the chat

**Comment by 01123581321345589144233** [comment]
try: ok found a workaround, go to the database:
sessions > bgcolour change the 6 to a higher value, Allow nulls? = yes
and save the row. login as guest is working
