### ISSUE TITLE
[Locale] Add locales for Hindi Language

### ISSUE THREAD

**Issue by fadkeabhi** [DanWin/le-chat-php#141]
@DanWin I would like to work on adding the Hindi Language locale to this repository.
Assign it me if possible.

**Comment by DanWin** [comment]
Hi @fadkeabhi , thank you for offering to work on this. You can use a translation tool such as Poedit to create a translation on your computer, with the language template in the repository: https://github.com/DanWin/le-chat-php/blob/master/locale/le-chat-php.pot
Alternatively you can also use my Weblate instance to submit a translation online. It will then automaticaly be added/updated here.  https://weblate.danwin1210.de/projects/DanWin/le-chat-php/hi/
Once the translation is ready, it needs to be added as an option to the chat.php script for inclusion.

**Comment by fadkeabhi** [comment]
@DanWin Thank you for assigning me this task. I wanted to let you know that I've started working on the Hindi translation process. I will keep you updated on my progress and reach out if I have any questions. Thanks again for your support!

**Comment by fadkeabhi** [comment]
Hey @DanWin i have created PR for same here https://github.com/DanWin/le-chat-php/pull/142. Take a look at it.

**Comment by DanWin** [comment]
Thanks a lot @fadkeabhi , I've just fixed a few double-spaces and included your translation in dba4f49
