### ISSUE TITLE
Vercel Deployment

### ISSUE THREAD

**Issue by gittyspirit** [DanWin/le-chat-php#150]
Is it possible to deploy this chat on PaaS platforms like Vercel? I don't have a stable homeserver or VPS yet.

**Comment by thealidev** [comment]
You can depoly it on php web hosting
Not vercel
Use infinity free for free

**Comment by DanWin** [comment]
Vercel doesn't offer PHP deployments from what I've checked in their documentation, so it won't be possible. It will work on almost any web hosting service, including free ones (although some of them block chats on free plans). You could also get a free VPS from one of the always free plans from for example Oracle Cloud.
