### ISSUE TITLE
failed to login admin?

### ISSUE THREAD

**Issue by jingjinghack** [DanWin/le-chat-php#3]
MySQL Version: 5.6.30
PHP Version: 5.6.22
i am running server is raspberry pi(OS raspbian)

nickname is: "jingjinghack"
password is: "opsb990.."
![2016-11-13 14-28-51](https://cloud.githubusercontent.com/assets/16219523/20244080/3a22be3e-a938-11e6-82eb-35ad705bae77.png)
![2016-11-13 14-31-54](https://cloud.githubusercontent.com/assets/16219523/20244098/d69137c8-a938-11e6-83bb-e500766b62b6.png)

**Comment by DanWin** [comment]
Thanks for pointing it out. There was a missing column in the initialization sql, which resulted in an error on creating the admin user. I just released a fix in version 1.22.1. Please run the following sql query manually and set it up again:
```DROP TABLE files, captcha, filter, ignored, inbox, linkfilter, members, messages, notes, sessions, settings;```

**Comment by jingjinghack** [comment]
thank you :)
