### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Wittles** [DanWin/le-chat-php#5]
I have included my DB, using wamp before I move over to a pi, I put in the DB settings and set it to 0(default), it soon as I go to active=setup it shows the admin password section, and just empties the out put soon as I add anything, so I look in the DB, its not written anything to the DB at all.

No errors at all its just not doing it, this is the version 1.23.1

From what I can see in the code I not seeing any of the setup section it just jumps to admin login.

PHP Version: 5.6.25
Server Software: Apache/2.4.23 (Win64) PHP/5.6.25 - Port defined for Apache: 80
Loaded Extensions :
apache2handler
bcmath
bz2
calendar
com_dotnet
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tokenizer
wddx
xdebug
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib
MySQL Version: 5.7.14

**Comment by DanWin** [comment]
Thanks!
Due to recent code changes, initialization wasn't routed properly.
This is fixed in the latest version: 1.23.2
