### ISSUE TITLE
Is it possible to change the superuser password with MySQL/MariaDB?

### ISSUE THREAD

**Issue by runazaz** [DanWin/le-chat-php#6]
Hello Daniel,

I am using the newest version of your Chat.
I forgot the password for the superuser.
Is it possible to change the password with help opf MySQL or MariaDB?

Thanks,
nonick

**Comment by DanWin** [comment]
Hello, yes that is possible with the following query:
UPDATE members SET passhash='output-of-script' WHERE nickname='my-user';
Use this Script to generate a new password hash, which you can then enter in the above query and run on your database:
```
<?php
echo password_hash('my-new-password', PASSWORD_DEFAULT)."\n";
?>
```
