### ISSUE TITLE
What if we start a new project?

### ISSUE THREAD

**Issue by cypherbits** [DanWin/le-chat-php#68]
Should we start a new chat project only compatible with PHP >= 7.4 using new PHP "strict" mode + objects and variable types + better security and encryption + better UI templates??

**Comment by whalehub** [comment]
@cypherbits I wouldn't be able to contribute to it with code because I'm not a programmer, but I could help out with writing documentation and bug testing.

**Comment by Deepnerd** [comment]
@cypherbits Awesome!

**Comment by cypherbits** [comment]
I don't have the time to start working alone on a new chat from ground up.
But I'm working on writing an encryption specification for the new chat and how it should work.
Here: https://github.com/cypherbits/papers/tree/master/le-chat-php

**Comment by falcon-36** [comment]
@cypherbits I like the idea and am happy to help. :)

**Comment by cypherbits** [comment]
New issue for tracking a remake in here: https://github.com/DanWin/le-chat-php/issues/80
