### ISSUE TITLE
Fatal error: No connection to database?

### ISSUE THREAD

**Issue by jingjinghack** [DanWin/le-chat-php#7]
I'm using MySQL 5.5.48
netstat -an:
```
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN
```
3306 port is opened, Why "No connection to database"?

**Comment by DanWin** [comment]
Did you make sure you have the correct login credentials in the configuration at the bottom of the script?
The database host is by default 'localhost', which would use a Unix socket to MySQL. If you want to connect via tcp, you will have to change the dbhost setting to '127.0.0.1'. If none of the above applies, it's also worth checking the error log of your web server. There might be a hint on what's going wrong.

**Comment by jingjinghack** [comment]
@DanWin 
> Did you make sure you have the correct login credentials in the configuration at the bottom of the script?

Yes.

> The database host is by default 'localhost', which would use a Unix socket to MySQL. If you want to connect via tcp, you will have to change the dbhost setting to '127.0.0.1'. If none of the above applies, it's also worth checking the error log of your web server. There might be a hint on what's going wrong.

Let me try.

**Comment by jingjinghack** [comment]
Solved.
Thanks!
