### ISSUE TITLE
Vulnerability: Embedded image XSS

### ISSUE THREAD

**Issue by falcon-36** [DanWin/le-chat-php#72]
Embedded images can cause unwanted and harmful GET requests.
For example:

`[img]http://example.com/chat.php?action=admin&do=clean&what=room`

**Comment by cypherbits** [comment]
The best way to fix issues like this should be replace all $_REQUEST by $_GET and all admin request by forms and $_POST.

**Comment by cypherbits** [comment]
This is fixed.

**Comment by DanWin** [comment]
Fixed completely in f5a051c
