### ISSUE TITLE
Error Setting Up

### ISSUE THREAD

**Issue by KillerFusky** [DanWin/le-chat-php#8]
I keep editing the configuration for the database then do chat.php?action=setup and nothing happens. Is there like a video I can see to set this up. Nothing works, only a blank page pops up.

**Comment by DanWin** [comment]
When you only get a blank page, you most likely have a syntax error after editing your file. Check your web server logs or run php from cli to retrieve an error message that could help you identify the issue.

**Comment by KillerFusky** [comment]
Idk what I did wrong by apparently 3rd times the charm.
