### ISSUE TITLE
Download `.txt` log of temporary chat.

### ISSUE THREAD

**Issue by fr33roam3r** [DanWin/le-chat-php#85]
It would be nice for the staff, members, and guests if there is a way to download the temporary chat (only what the user can see) in case there is something that needs to be recorded (without taking up space on the server).

**Comment by rexzooly** [comment]
I don't believe giving users the means to record the chat is a safe idea, also this so called recorded version to even be a fair version would need a MD5 and so on and this would have to be stored on the server to even show that this record was real and not tampered with.

**Comment by fr33roam3r** [comment]
True
