### ISSUE TITLE
Application  Is highly questionable

### ISSUE THREAD

**Issue by bakertaylor28** [DanWin/le-chat-php#88]
The use of this application on the internet is highly questionable. Not sure that this is the best app to use when there are more solid options out there such as email and the like.

**Comment by cypherbits** [comment]
> The use of this application on the internet is highly questionable. Not sure that this is the best app to use when there are more solid options out there such as email and the like. 

Don't understand. This is just a php simple group chat that do not require javascript. Not an email replacement. Like you said there are alternatives but many users still use this chat...

**Comment by DanWin** [comment]
Using the internet the way it is in general is highly questionable. Nothing is perfect, everywhere people can steal your data and whatever you post can be recorded and/or read by third parties, Unless you operate your own email server, you most likely have to trust your email provider with your data, just as with this chat application you need to trust your chat server operator.
I'm closing this issue as it has no relevant input to further improve it.
