### ISSUE TITLE
File types can be manipulated.

### ISSUE THREAD

**Issue by Peter-Griffin** [DanWin/le-chat-php#89]
**$_FILES['file']['type'] is send by the user therefore it can not be trusted!**

**Line 3034-3038:**
```
if(!empty($_FILES['file']['type']) && preg_match('~^[a-z0-9/\-.+]*$~i', $_FILES['file']['type'])){
	$type=$_FILES['file']['type'];
}else{
	$type='application/octet-stream';
}
```

**Line 3034-3038 should be replaced with:**
`$type=mime_content_type($_FILES['file']['tmp_name']);`

**Comment by DanWin** [comment]
Thanks, added this in 45035eb
