### ISSUE TITLE
Plis Help ME

### ISSUE THREAD

**Issue by Diego93777** [DanWin/le-chat-php#9]
Hello, how can I put to the side of the chat the list of connected users

**Comment by jorgedx** [comment]
nice question :+1:

**Comment by DanWin** [comment]
Sorry for the delay. Do you want to move the list of chatters from the top to the right side, like I did on my site?
You can do that by adding the following CSS in the setup:
.messages #chatters {display: block; float:right; width: 20%; overflow-y: auto; position:fixed; right:0px; max-height:100%; bottom:2em; top:2em;}
.messages #chatters td, #chatters tr, #chatters th {display: table-row; width: 100%!important;}
.messages #chatters table a {display: table-row; line-height: 0;}
