### ISSUE TITLE
Installation with SQLite database is broken

### ISSUE THREAD

**Issue by DanWin** [DanWin/le-chat-php#93]
SQL error thrown in install step renders the script unusable.

**Comment by LexShadow** [comment]
There is still a bug, if I set it to sqlite as I don't have mysql for less attack vectors and resources but soon as I try set it up I get 

Warning: PDO::prepare(): SQLSTATE[HY000]: General error: 1 no such table: 

The sqlite file is created but after that it's does that error, the part that installs the db seems to be missing I see a trigger for it ever.
